### ISSUE TITLE
Can't install matplotlib

### ISSUE THREAD

**Issue by sudhanshu196r** [SnazzyCoder/HMS-NMS#6]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for matplotlib
  Running setup.py clean for matplotlib
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\sudha\AppData\Local\Temp\pip-install-v62djluw\matplotlib_c968c02102d3415eae7d405bfa2c0c3e\setup.py", line 247, in <module>
          long_description=long_description,
      NameError: name 'long_description' is not defined
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for matplotlib
Failed to build matplotlib
Installing collected packages: matplotlib
  Running setup.py install for matplotlib ... error
  error: subprocess-exited-with-error

  × Running setup.py install for matplotlib did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]

      Edit setup.cfg to change the build options; suppress output with --quiet.

      BUILDING MATPLOTLIB
        matplotlib: yes [3.2.0]
            python: yes [3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC
                        v.1929 64 bit (AMD64)]]
          platform: yes [win32]
       sample_data: yes [installing]
             tests: no  [skipping due to configuration]
               agg: yes [installing]
             tkagg: yes [installing; run-time loading from Python Tcl/Tk]
            macosx: no  [Mac OS-X only]

      running install
      running build
      running build_py
      copying lib\matplotlib\mpl-data\matplotlibrc -> build\lib.win-amd64-3.9\matplotlib\mpl-data
      UPDATING build\lib.win-amd64-3.9\matplotlib\_version.py
      set build\lib.win-amd64-3.9\matplotlib\_version.py to '3.2.0'
      running build_ext
      building 'matplotlib.ft2font' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> matplotlib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by CrypticXT** [comment]
Try to install Microsoft C++ Build Tools should fix that issue

**Comment by DocZeus** [comment]
no solution yet? (I have microsoft C++ build tools installed)

**Comment by Just-Moh-it** [comment]
Matplotlib isn't really an important part of the app, and I really should have considered lighter alternatives... For the meantime, if you're unable to get Matplotlib to work, just globally find the word Matplotlib in the project folder on your text-editor and remove the code part that's executed by Matplotlib (only in the dashboard pane I think)

**Comment by sudhanshu196r** [comment]
Done
